apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-eth1-policy 
spec:
  nodeSelector: 
    kubernetes.io/hostname: fede-virt-worker-0.karmalabs.com 
  maxUnavailable: 3 
  desiredState:
    interfaces: