apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress
spec:
  selector:
    matchLabels:
      app: egress
  template:
    metadata:
      labels:
        app: egress
    spec:
      containers:
      - name: egress
        image: quay.io/fpaoline/fedoranet:1.0
        command:
          - sleep
          - inf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx1
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  annotations:
    metallb.universe.tf/address-pool: second-pool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: egress
  annotations:
    metallb.universe.tf/address-pool: third-pool
    k8s.ovn.org/egress-service: '{"nodeSelector":{"matchLabels":{"kubernetes.io/hostname": "ovn-worker"}}}'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: egress
  type: LoadBalancer
