apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: node1policy 
spec:
  nodeSelector: 
    kubernetes.io/hostname: fede-virt-worker-1.karmalabs.corp
  maxUnavailable: 3 
  desiredState:
    interfaces:
      - name: ens4
        state: up
        ipv4:
          address:
          - ip: 192.168.130.3
            prefix-length: 24
          dhcp: false
          enabled: true
