apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: servicereturnpath 
spec:
  nodeSelector: 
    vrf: "true"
  maxUnavailable: 3 
  desiredState:
    route-rules: # Note this is gonna be set by ovnk and depends on the clusterip
      config:
        - ip-from: 172.30.80.81 
          route-table: 200
          priority: 1002

