apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vrfpolicy 
spec:
  nodeSelector: 
    vrf: "true"
  maxUnavailable: 3 
  desiredState:
    interfaces:
      - name: ens9veth-def
        type: veth
        state: up
        ipv4:
          address:
            - ip: 192.169.2.1
              prefix-length: 24
          dhcp: false
          enabled: true
        veth:
          peer: ens9veth-vrf
      - name: ens9veth-vrf
        type: veth
        state: up
        ipv4:
          address:
            - ip: 192.169.2.2
              prefix-length: 24
          dhcp: false
          enabled: true
        veth:
          peer: ens9veth-def
      - name: ens9vrf
        type: vrf
        state: up
        vrf:
          port:
            - ens9veth-vrf
            - ens9
          route-table-id: 2
    routes:
      config:
        - destination: 0.0.0.0/0
          metric: 150
          next-hop-address: 192.168.130.1
          next-hop-interface: ens9
          table-id: 2
        - destination: 172.30.0.0/16
          metric: 150
          next-hop-address: 192.169.2.1
          next-hop-interface: ens9veth-vrf
          table-id: 2
        - destination: 10.135.0.0/16
          metric: 150
          next-hop-address: 192.169.2.1
          next-hop-interface: ens9veth-vrf
          table-id: 2
        - destination: 0.0.0.0/0
          metric: 150
          next-hop-address: 192.169.2.2
          next-hop-interface: ens9veth-def
          table-id: 200
