# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.box = "fedora/36-cloud-base"
    config.vm.network "private_network", ip: "10.111.221.11", auto_config: false
    config.vm.provider "libvirt" do |vm|
      vm.qemu_use_session = false
      vm.memory = "1024"
    end
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provision "shell", inline: <<-SHELL
      dnf install -y nmstate
    SHELL
  end
